/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#d3e4fe',
        'primary-fixed-dim': '#b4c5ff',
        'on-secondary-container': '#54647a',
        'on-primary-fixed-variant': '#003ea7',
        'primary-fixed': '#dbe1ff',
        'on-primary-container': '#eeefff',
        'primary-container': '#2463eb',
        'secondary-container': '#d0e1fb',
        'tertiary': '#006242',
        'on-secondary': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'secondary-fixed-dim': '#b7c8e1',
        'secondary': '#505f76',
        'surface-container-high': '#e2e7ff',
        'on-background': '#131b2e',
        'surface-container-low': '#f2f3ff',
        'on-tertiary-fixed-variant': '#005236',
        'surface-dim': '#d2d9f4',
        'tertiary-container': '#007d55',
        'inverse-on-surface': '#eef0ff',
        'on-tertiary-fixed': '#002113',
        'on-surface': '#131b2e',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#00174b',
        'outline-variant': '#c3c6d7',
        'on-tertiary': '#ffffff',
        'surface-container': '#eaedff',
        'on-secondary-fixed': '#0b1c30',
        'tertiary-fixed': '#6ffbbe',
        'on-surface-variant': '#434655',
        'on-tertiary-container': '#bdffdb',
        'tertiary-fixed-dim': '#4edea3',
        'surface-tint': '#0053da',
        'outline': '#737686',
        'error-container': '#ffdad6',
        'surface': '#faf8ff',
        'inverse-surface': '#283044',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'primary': '#004bc6',
        'on-secondary-fixed-variant': '#38485d',
        'surface-container-highest': '#dae2fd',
        'error': '#ba1a1a',
        'surface-bright': '#faf8ff',
        'on-error': '#ffffff',
        'background': '#faf8ff',
        'surface-variant': '#dae2fd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        gutter: '20px',
        lg: '24px',
        'container-max': '1280px',
        xl: '48px',
        sm: '8px',
        unit: '4px',
        md: '16px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'code-sm': ['monospace'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'code-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
